# Generated by Django 3.1.6 on 2021-03-11 01:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='form_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
