# Generated by Django 3.1.7 on 2021-04-01 16:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_work_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('name', wagtail.core.blocks.CharBlock(form_classname='full title')), ('description', wagtail.core.blocks.RichTextBlock()), ('text', wagtail.core.blocks.CharBlock())]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='work_content',
            field=wagtail.core.fields.StreamField([('work_heading', wagtail.core.blocks.StructBlock([('section_title', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.CharBlock(required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('subheading_2', wagtail.core.blocks.CharBlock(required=False)), ('paragraph_2', wagtail.core.blocks.RichTextBlock(required=False))])), ('work', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('category', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock())]))]),
        ),
    ]
