# Generated by Django 3.1.7 on 2021-04-01 18:18

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210401_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='interests',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='links',
            field=models.URLField(default='a'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_i_build',
            field=wagtail.core.fields.RichTextField(default='a'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='who_i_am',
            field=wagtail.core.fields.RichTextField(default='a'),
        ),
    ]
