# Generated by Django 3.1.7 on 2021-04-02 19:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210401_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.StreamField([('profile_image', wagtail.images.blocks.ImageChooserBlock(max_num=1)), ('about', wagtail.core.blocks.StructBlock([('profile_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('links', wagtail.core.blocks.StructBlock([('wesbsite_link', wagtail.core.blocks.URLBlock(required=False))])), ('skills', wagtail.core.blocks.StructBlock([('skills', wagtail.core.blocks.CharBlock(required=False))])), ('interests', wagtail.core.blocks.StructBlock([('interests', wagtail.core.blocks.CharBlock(required=False))])), ('who_i_am', wagtail.core.blocks.RichTextBlock(required=False)), ('what_i_build', wagtail.core.blocks.RichTextBlock(required=False))], max_num=1))]),
        ),
    ]
