# Generated by Django 3.1.6 on 2021-02-11 19:47

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('insights', '0004_insightspagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='insights.InsightsPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
