# Generated by Django 3.1.6 on 2021-02-11 20:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('insights', '0007_blogcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='InsightsCategory',
        ),
        migrations.AddField(
            model_name='insightspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='insights.InsightsCategory'),
        ),
    ]
