# Generated by Django 3.1.6 on 2021-03-04 21:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0009_auto_20210211_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insightscategory',
            options={'verbose_name_plural': 'insights categories'},
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('raw_HTML', wagtail.core.blocks.RawHTMLBlock()), ('block_quote', wagtail.core.blocks.BlockQuoteBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())]),
        ),
    ]
