# Generated by Django 3.1.6 on 2021-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0010_auto_20210304_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insightscategory',
            options={'ordering': ['name'], 'verbose_name': 'Insights Category', 'verbose_name_plural': 'Insights Categories'},
        ),
        migrations.AddField(
            model_name='insightscategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='hello', help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
        ),
    ]
