# Generated by Django 3.1.7 on 2021-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0011_auto_20210304_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightscategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
        ),
    ]
