# Generated by Django 3.1.7 on 2021-03-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('insights', '0015_insightsauthorsorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsauthor',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
