# Generated by Django 3.1.7 on 2021-04-01 18:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0016_auto_20210331_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightsauthor',
            name='social_media',
            field=wagtail.core.fields.RichTextField(default='a'),
        ),
        migrations.AlterField(
            model_name='insightsauthor',
            name='website',
            field=wagtail.core.fields.StreamField([('website_url', wagtail.core.blocks.URLBlock()), ('website_icon', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
