# Generated by Django 3.1.7 on 2021-04-01 18:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0017_auto_20210401_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsauthor',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social_media_link', wagtail.core.blocks.URLBlock(default='A')), ('social_media_icon', wagtail.images.blocks.ImageChooserBlock(default='A'))]),
        ),
    ]
