# Generated by Django 3.1.7 on 2021-04-02 17:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0020_auto_20210402_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsauthor',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social_media', wagtail.core.blocks.StructBlock([('social_media_name', wagtail.core.blocks.CharBlock(default='abc', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='insightsauthor',
            name='website',
            field=wagtail.core.fields.StreamField([('website', wagtail.core.blocks.StructBlock([('website_name', wagtail.core.blocks.CharBlock(required=False)), ('website_links', wagtail.core.blocks.URLBlock()), ('website_icon', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
