# Generated by Django 3.1.7 on 2021-04-02 19:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0021_auto_20210402_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsauthor',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social_media_block', wagtail.core.blocks.StructBlock([('social_media_name', wagtail.core.blocks.CharBlock()), ('social_media_link', wagtail.core.blocks.URLBlock())]))], blank=True, null=True, verbose_name='Social Media & Other'),
        ),
        migrations.AlterField(
            model_name='insightsauthor',
            name='website',
            field=wagtail.core.fields.StreamField([('website_block', wagtail.core.blocks.StructBlock([('website_name', wagtail.core.blocks.CharBlock()), ('website_link', wagtail.core.blocks.URLBlock())], max_num=1))], blank=True, null=True),
        ),
    ]
